import test from 'node:test';
import assert from 'node:assert/strict';
import {Readable} from 'node:stream';
import {createApp} from '../server/index.mjs';
const env={GOOGLE_CLIENT_ID:'client',GOOGLE_CLIENT_SECRET:'secret',APP_ORIGIN:'https://ws.example',GOOGLE_ALLOWED_EMAILS:'pilot@example.com',YANDEX_API_KEY:'paid-secret',YANDEX_FOLDER_ID:'folder',AI_USER_REQUESTS_PER_DAY:'1'};
function request(app,url,method='GET',headers={},body){return new Promise((resolve,reject)=>{const req=Readable.from(body===undefined?[]:[JSON.stringify(body)]);Object.assign(req,{url,method,headers:{host:'ws.example',...headers}});const out={};let status;const res={setHeader:(k,v)=>out[k.toLowerCase()]=v,writeHead:(s,h)=>{status=s;for(const [k,v] of Object.entries(h||{}))out[k.toLowerCase()]=v},end:b=>resolve({status,headers:out,body:String(b||''),json:()=>JSON.parse(b)})};Promise.resolve(app.listeners('request')[0](req,res)).catch(reject)})}
function setup(){let calls=0;const app=createApp({env,authDbPath:':memory:',authFetchFn:async url=>new Response(JSON.stringify(url.includes('/token')?{access_token:'access'}:{sub:'1',email:'pilot@example.com',email_verified:true,name:'Pilot'})),fetchFn:async()=>{calls++;return new Response('ID3audio')}});return {app,calls:()=>calls}}
async function login(app){const r=await request(app,'/auth/google'),state=new URL(r.headers.location).searchParams.get('state');const c=await request(app,'/auth/google/callback?state='+state+'&code=code','GET',{cookie:r.headers['set-cookie'].split(';')[0]});assert.equal(c.status,303);return c.headers['set-cookie'][0].split(';')[0]}
test('anonymous paid API calls are rejected before reading input or billing',async()=>{const {app,calls}=setup();try{for(const path of ['/api/guide','/api/speech'])assert.equal((await request(app,path,'POST',{},{})).status,401);assert.equal(calls(),0);assert.equal((await request(app,'/api/config')).json().ai,false);assert.equal((await request(app,'/api/session')).json().user,null)}finally{app.emit('close')}});
test('session gates paid API and requires canonical Origin; logout revokes access',async()=>{const {app,calls}=setup();try{const cookie=await login(app);assert.equal((await request(app,'/api/session','GET',{cookie})).json().user.email,'pilot@example.com');assert.equal((await request(app,'/api/config','GET',{cookie})).json().ai,true);for(const origin of [undefined,'https://evil.example'])assert.equal((await request(app,'/api/speech','POST',{cookie,...(origin?{origin}:{})},{text:'Hello'})).status,403);assert.equal(calls(),0);assert.equal((await request(app,'/api/speech','POST',{cookie,origin:env.APP_ORIGIN,'content-type':'application/json'},{text:'Hello'})).status,200);assert.equal(calls(),1);assert.equal((await request(app,'/auth/logout','POST',{cookie,origin:'https://evil.example'})).status,403);assert.equal((await request(app,'/auth/logout','POST',{cookie,origin:env.APP_ORIGIN})).status,200);assert.equal((await request(app,'/api/speech','POST',{cookie,origin:env.APP_ORIGIN},{text:'Hello'})).status,401)}finally{app.emit('close')}});
test('OAuth callback rejects missing binding and never exposes provider secrets',async()=>{const {app,calls}=setup();try{const r=await request(app,'/auth/google/callback?code=private&state=bad');assert.equal(r.status,303);assert.equal(r.headers.location,'/?auth_error=1');assert.equal(calls(),0);assert.doesNotMatch(JSON.stringify(r),/paid-secret|private/)}finally{app.emit('close')}});
test('canonical origin works behind a proxy with a rewritten Host',async()=>{const {app}=setup();try{const cookie=await login(app);assert.equal((await request(app,'/api/speech','POST',{host:'internal:5173',cookie,origin:env.APP_ORIGIN,'content-type':'application/json'},{text:'Hello'})).status,200)}finally{app.emit('close')}});
test('daily HTTP quota rejects further calls without billing providers',async()=>{const {app,calls}=setup();try{const cookie=await login(app),headers={cookie,origin:env.APP_ORIGIN,'content-type':'application/json'};assert.equal((await request(app,'/api/guide','POST',headers,{})).status,400);assert.equal((await request(app,'/api/guide','POST',headers,{})).status,429);assert.equal(calls(),0);assert.equal((await request(app,'/api/session','GET',{cookie})).json().usage.ai.remaining,0)}finally{app.emit('close')}});
