import test from 'node:test';
import assert from 'node:assert/strict';
import {createAuth} from '../server/auth.mjs';
const env={GOOGLE_CLIENT_ID:'client',GOOGLE_CLIENT_SECRET:'secret',APP_ORIGIN:'https://ws.example',GOOGLE_ALLOWED_EMAILS:'pilot@example.com'};
function setup(extra={},identity={sub:'google-1',email:'pilot@example.com',email_verified:true,name:'Pilot'}){
 let time=Date.now(),calls=[];
 const auth=createAuth({env:{...env,...extra},dbPath:':memory:',now:()=>time,fetchFn:async(url,options)=>{calls.push({url,options});return new Response(JSON.stringify(url.includes('/token')?{access_token:'access'}:identity))}});
 return {auth,calls,advance:ms=>time+=ms};
}
async function login(auth){const started=auth.start();const url=new URL(started.location);const state=url.searchParams.get('state');const result=await auth.callback(new URL('https://ws.example/auth/google/callback?state='+state+'&code=code'),started.cookie.split(';')[0]);return {started,result,cookie:result.cookie.split(';')[0]}}
test('Google login binds state, uses PKCE, stores a session and revokes logout',async()=>{const {auth,calls}=setup();try{const {cookie,started}=await login(auth);const url=new URL(started.location);assert.equal(url.origin,'https://accounts.google.com');assert.equal(url.searchParams.get('code_challenge_method'),'S256');assert.match(started.cookie,/HttpOnly; Secure; SameSite=Lax/);assert.equal(new URLSearchParams(calls[0].options.body).get('redirect_uri'),'https://ws.example/auth/google/callback');assert.ok(new URLSearchParams(calls[0].options.body).get('code_verifier'));assert.equal(auth.session(cookie).email,'pilot@example.com');auth.logout(cookie);assert.equal(auth.session(cookie),null)}finally{auth.close()}});
test('wrong browser, missing state and replay cannot create a session',async()=>{const {auth,calls}=setup();try{const start=auth.start(),state=new URL(start.location).searchParams.get('state'),url=new URL('https://ws.example/auth/google/callback?state='+state+'&code=code');await assert.rejects(auth.callback(url,''));assert.equal(calls.length,0);await auth.callback(url,start.cookie.split(';')[0]);await assert.rejects(auth.callback(url,start.cookie.split(';')[0]));await assert.rejects(auth.callback(new URL('https://ws.example/auth/google/callback?code=code'),'anything'))}finally{auth.close()}});
test('unverified or uninvited identities are refused',async()=>{for(const identity of [{sub:'x',email:'pilot@example.com',email_verified:false},{sub:'x',email:'stranger@example.com',email_verified:true}]){const {auth}=setup({},identity);try{await assert.rejects(login(auth))}finally{auth.close()}}});
test('session expires and daily quota resets at next UTC date',async()=>{const {auth,advance}=setup({AI_USER_REQUESTS_PER_DAY:'1'});try{const {cookie}=await login(auth),user=auth.session(cookie);auth.consume(user,'ai');assert.throws(()=>auth.consume(user,'ai'),{status:429});advance(86400000);auth.consume(user,'ai');advance(7*86400000);assert.equal(auth.session(cookie),null)}finally{auth.close()}});
test('unconfigured authentication fails closed',()=>{const auth=createAuth({env:{}});assert.equal(auth.enabled,false);assert.equal(auth.session(''),null);assert.throws(()=>auth.start(),{status:503})});
test('sessions and daily quotas survive a process restart',async()=>{
 const {mkdtempSync,rmSync}=await import('node:fs');const {tmpdir}=await import('node:os');const {join}=await import('node:path');
 const dir=mkdtempSync(join(tmpdir(),'waystory-auth-')),dbPath=join(dir,'auth.sqlite');
 let auth=createAuth({env:{...env,AI_USER_REQUESTS_PER_DAY:'1'},dbPath,fetchFn:async url=>new Response(JSON.stringify(url.includes('/token')?{access_token:'access'}:{sub:'persistent',email:'pilot@example.com',email_verified:true}))});
 try{const {cookie}=await login(auth);auth.consume(auth.session(cookie),'ai');auth.close();auth=createAuth({env:{...env,AI_USER_REQUESTS_PER_DAY:'1'},dbPath});assert.equal(auth.session(cookie).id,'persistent');assert.throws(()=>auth.consume(auth.session(cookie),'ai'),{status:429});assert.equal(auth.usage(auth.session(cookie)).ai.remaining,0)}finally{auth.close();rmSync(dir,{recursive:true,force:true})}
});
test('global daily quota applies across users and cannot be bypassed by logout',async()=>{const {auth}=setup({AI_REQUESTS_PER_DAY:'1'});try{const {cookie}=await login(auth),user=auth.session(cookie);auth.consume(user,'ai');auth.logout(cookie);assert.throws(()=>auth.consume({id:'another-user'},'ai'),{status:429})}finally{auth.close()}});
test('expired OAuth state and bad provider response fail closed',async()=>{const {auth,advance}=setup();try{const start=auth.start();advance(11*60000);await assert.rejects(auth.callback(new URL('https://ws.example/auth/google/callback?code=x&state='+new URL(start.location).searchParams.get('state')),start.cookie.split(';')[0]))}finally{auth.close()}});
test('production origin cannot be insecure or contain a redirect path',()=>{for(const APP_ORIGIN of ['http://ws.example','https://ws.example/path','https://ws.example/'])assert.throws(()=>createAuth({env:{...env,NODE_ENV:'production',APP_ORIGIN},dbPath:':memory:'}))});
test('empty invitation list denies every identity',async()=>{const {auth}=setup({GOOGLE_ALLOWED_EMAILS:''});try{await assert.rejects(login(auth))}finally{auth.close()}});
test('removing invitation rejects an existing persistent session',async()=>{const {mkdtempSync,rmSync}=await import('node:fs');const {tmpdir}=await import('node:os');const {join}=await import('node:path');const dir=mkdtempSync(join(tmpdir(),'waystory-revoke-')),dbPath=join(dir,'auth.sqlite');let auth=createAuth({env,dbPath,fetchFn:async url=>new Response(JSON.stringify(url.includes('/token')?{access_token:'access'}:{sub:'existing',email:'pilot@example.com',email_verified:true}))});try{const {cookie}=await login(auth);auth.close();auth=createAuth({env:{...env,GOOGLE_ALLOWED_EMAILS:''},dbPath});assert.equal(auth.session(cookie),null)}finally{auth.close();rmSync(dir,{recursive:true,force:true})}});
