import test from 'node:test';
import assert from 'node:assert/strict';
import {Readable} from 'node:stream';
import {createApp} from '../server/index.mjs';
function request(app,body,origin){return new Promise((resolve,reject)=>{const req=Readable.from([JSON.stringify(body)]);Object.assign(req,{url:'/api/speech',method:'POST',headers:{host:'localhost','content-type':'application/json',...(origin?{origin}: {})}});let status;const res={setHeader(){},writeHead:s=>status=s,end:body=>resolve({status,body})};Promise.resolve(app.listeners('request')[0](req,res)).catch(reject)})}
const env={YANDEX_API_KEY:'secret',YANDEX_FOLDER_ID:'folder',TTS_REQUESTS_PER_HOUR:'1'};
test('cloud speech returns MP3 and reuses cached text without another paid request',async()=>{let calls=0;const app=createApp({env,fetchFn:async(url,o)=>{calls++;assert.match(url,/tts:synthesize/);assert.equal(new URLSearchParams(o.body).get('format'),'mp3');assert.equal(new URLSearchParams(o.body).has('folderId'),false);return new Response('ID3audio',{headers:{'content-type':'audio/mpeg'}})}});const a=await request(app,{text:'Привет'});assert.equal(a.status,200);assert.equal(a.body.toString(),'ID3audio');assert.equal((await request(app,{text:'Привет'})).status,200);assert.equal(calls,1);assert.equal((await request(app,{text:'Другой текст'})).status,429)});
test('speech validates input and origin before calling provider',async()=>{let calls=0;const app=createApp({env,fetchFn:async()=>{calls++;return new Response('ID3')}});assert.equal((await request(app,{text:'x'.repeat(1601)})).status,400);assert.equal((await request(app,{text:'test'},'https://evil.test')).status,403);assert.equal(calls,0)});
test('missing SpeechKit permission gives actionable error without leaking credentials',async()=>{const app=createApp({env,fetchFn:async()=>new Response('secret',{status:403})});const r=await request(app,{text:'Тест'});assert.equal(r.status,503);assert.match(r.body.toString(),/SpeechKit/);assert.doesNotMatch(r.body.toString(),/secret/)});
test('speech-only credentials advertise cloud audio even without AI credentials',async()=>{const app=createApp({env:{YANDEX_TTS_API_KEY:'speech-secret'}});const config=await new Promise(resolve=>app.listeners('request')[0]({url:'/api/config',method:'GET',headers:{host:'localhost'}},{setHeader(){},writeHead(){},end:b=>resolve(JSON.parse(b))}));assert.equal(config.ai,false);assert.equal(config.tts,true)});
test('English speech uses an English voice and has a separate audio cache',async()=>{let calls=0;const app=createApp({env:{...env,TTS_REQUESTS_PER_HOUR:'5'},fetchFn:async(url,o)=>{calls++;const p=new URLSearchParams(o.body);assert.equal(p.get('lang'),calls===1?'ru-RU':'en-US');assert.equal(p.get('voice'),calls===1?'filipp':'john');return new Response('ID3audio')}});assert.equal((await request(app,{text:'Paris',language:'ru'})).status,200);assert.equal((await request(app,{text:'Paris',language:'en'})).status,200);assert.equal(calls,2)});
